<?php require("../../base.php"); ?>
<?php require("tutorial-regex-title.php"); ?>
<?php require("../../header.php"); ?>
<?php require("tutorial-regex-header.php"); ?>
<?php require("../../body.php"); ?>
<?php require("tutorial-regex-menu.php"); ?>
<?php require("tutorial-regex-sub-menu.php"); ?>
<?php require("tutorial-regex-content.php"); ?>
<?php require("../../footer.php"); ?>
